### ISSUE TITLE
Send parameters by header

### ISSUE THREAD

**Issue by juniorsml** [NathanaelA/nativescript-websockets#10]
Hi NathanaelA ! Thanks for implement this module for community.

Is there any way to send parameters on header in the moment of connection?

**Comment by NathanaelA** [comment]
Sorry, I don't have an easy way exposed to do this yet.   This could be added fairly easily I believe.

**Comment by NathanaelA** [comment]
@alg created a pull request that fixed this issue.  So this is now supported in the new v1.20 that has been pushed to npm.
