### ISSUE TITLE
Error SLF4J

### ISSUE THREAD

**Issue by Alberz** [NathanaelA/nativescript-websockets#102]
I have started to use this "@master.technology/websockets" and "vue-native-websocket" library to manage websockets. When I run my app in debug mode, I get the next error:

**Error:**
System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

If I change to the old library "nativescript-websockets" I don´t get the SLF4J error.

I am using NS8 android platform

**Comment by gayatri-kadam** [comment]
I get the same error with nativescript angular. I just wanted to confirm if it does effect the websocket connection or not, because I am unable to use the "Advanced Interface" and I am not sure if it is because of this error.

**Comment by NathanaelA** [comment]
It attempts to call org.slf4j logging, to log from the native code.  However, in the release this is not included so it fails and then tells you it will do NOP (no logging).    It has no material effect on if anything works, it just is letting you know that logging from the native java android code is disabled.

As for why it just started appearing, the newer version uses a newer version of the native library, but this is not a "bug" or a issue that effects anything beyond debug logging of the native component.
