### ISSUE TITLE
With NativeScript 2.0.1, angular 2 typescript getting an error

### ISSUE THREAD

**Issue by karthik1516** [NathanaelA/nativescript-websockets#14]
I have the simple browser based interface code as suggested by your Readme.md, in my app.component.ts file and I get the following error. Can you please help?

TypeError: Cannot read property 'client' of undefined
File "<unknown>, line 1, column 265

StackTrace:
  Frame: function:',file:'/data/.../tns/modules/nativescript-websockets/websockets.js', line: 77, column:36
  Frame: function: 'require', file', line:1, column:266
  .....

**Comment by NathanaelA** [comment]
This appears as if NativeScript has not compiled in the WebSockets.   
I'm assuming you installed the plugin like so: 
**tns plugin add nativescript-websockets**

The fix assuming you have already done that; is the following:
**tns platform remove android**
then
**tns plafrom add android**

Then try running it.

**Comment by karthik1516** [comment]
Thanks so much Nathanael for your quick response. Your tip, helped me resolve the issue and now it works great.

Here is what I did:

tns plugin remove nativescript-websockets
tns platform remove android
tns plugin add nativescript-websockets
tns platform add android
tns build android
tns run android

**Comment by yss14** [comment]
Thanks, this steps also help fixing the error `JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate` on iOS :)

**Comment by chenzhiyuanthu** [comment]
> Thanks, this steps also help fixing the error `JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate` on iOS :)

@yss14 Hey, man. I just ran into the same situation. `ReferenceError: Can't find variable: PSWebSocketDelegate` when I run `tns preview --bundle`. How did you solve it?

**Comment by chenzhiyuanthu** [comment]
> Thanks, this steps also help fixing the error `JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate` on iOS :)

@yss14 Btw, I've already tried that "remove plugin, then remove platform, then install both" method...

**Comment by stevethomas** [comment]
For it's worth, I just lost a few hours on this to discover that anything listed in `devDependencies` in `package.json` does not trigger the Podfile installation step during build or run (on Nativescript-Vue at least). 

So make sure `@nativescript-pusher/channels` and others are listed in `dependencies`.

**Comment by NathanaelA** [comment]
Yes, `DevDependencies` are used for building the app; not during running of app.

**Comment by mrkvn** [comment]
I'm encountering this error : `JS ERROR ReferenceError: Can't find variable: PSWebSocketDelegate` after running `ns preview`. I don't have access to a mac but I have iPhone, hence the preview. I'm not sure if there would be no error when using an `ios emulator` or connecting iPhone to a mac. Also tried in nativescript playground, installed `nativescript-websockets`, same error.

**Comment by NathanaelA** [comment]
The preview app does not support native dependencies.    So this won't work on the playground or via the `ns preview` command.

**Comment by mrkvn** [comment]
Thanks. Appreciate the fast response. Sorry to ask here, very much off topic (please bear in mind that I'm noob and trying out things), but I don't have access to a mac. I just have my iphone. The only option that I can see that could work is an OSX VM, which again I'm not familiar with much. My question is (it's completely fine if you can't answer me here, can I dm you anywhere? :)) does ios emulator works in an OSX VM or do I need to connect my iphone to the VM? How does that work?

**Comment by NathanaelA** [comment]
iOS emulator works in a VM and your phone should also connect to a OSX VM.
