### ISSUE TITLE
does Protocols support ["mqtt"]?

### ISSUE THREAD

**Issue by codeHui** [NathanaelA/nativescript-websockets#15]
in my test,the same code of 'new WebSocket("ws://test.xxxxxx.cc:52184/mqtt", **["mqtt"]**);',that can be opened on brower,but failed in "nativescript-websockets";
 and code of 'new WebSocket("ws://xxxxxx") is ok

I notice ""The sending of Protocols support is not fully implemented on both platforms. Do not depend on this; it only partially works..""

I want to make sure if ["mqtt"] is suppored,thank you

**Comment by NathanaelA** [comment]
Not sure what mqtt is; but if you are passing "mqtt" as the protocol; then the receiving side is probably expecting mqtt being sent and so it is probably closing the connection when it doesn't get the a "mqtt" in the protocol list.   Like I said in the docs; protocol support (i.e. sending and verifying a protocol) is not implemented; so if the SERVER is requiring "mqtt" then until this feature is added; it won't work unless you change the server to allow no protocol to work...

**Comment by NathanaelA** [comment]
Should be now supported in v1.4.0
