### ISSUE TITLE
Connection refused on android

### ISSUE THREAD

**Issue by yss14** [NathanaelA/nativescript-websockets#16]
Hi there!
Thanks for this great plugin. I just tested it with your basic example and set up a little echo server with node on my local machine. On iOS it works great, but on Android the connection can't be established because of connection refuse.

```
JS: The socket had an error java.net.ConnectException: failed to connect to /127.0.0.1 (port 8181) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
JS: The Socket was Closed: -1 failed to connect to /127.0.0.1 (port 8181) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
```

Do I have to consider some special treatment for the android platform?

**Comment by NathanaelA** [comment]
It should work out of the box.  But you need to make sure you are using the latest WS dialect on your server. I just rebuilt my CrossCommunicator app under NS 2.3 and it connected fine on my android device to my WS server.  So WS is working fine on android...

BTW: The error message you are getting Connection Refused means the port 8181 is NOT responding.  So are you sure you set your server onto that port and on localhost, not an external ip.

**Comment by NathanaelA** [comment]
I have tested this again today 2018-05-28 on both ios and android and had no issues.
