### ISSUE TITLE
Error while running app in android

### ISSUE THREAD

**Issue by SumanSingh4** [NathanaelA/nativescript-websockets#24]
import { Component, OnInit, OnDestroy, NgZone } from "@angular/core";
require("nativescript-websockets");
 
@Component({
    selector: "my-app",
    templateUrl: "app.component.html",
})
export class AppComponent implements OnInit, OnDestroy {
 
    private socket: any;
    public messages: Array<any>;
    public chatBox: string;
 
    public constructor(private zone: NgZone) {
        this.socket = new WebSocket("http://192.168.3.41:2018/", []);
        this.messages = [];
        this.chatBox = "";
    }
 
    public ngOnInit() {
        this.socket.addEventListener('open', event => {
            this.zone.run(() => {
                this.messages.push({content: "Welcome to the chat!"});
            });
        });
        this.socket.addEventListener('message', event => {
            this.zone.run(() => {
                this.messages.push(JSON.parse(event.data));
            });
        });
        this.socket.addEventListener('close', event => {
            this.zone.run(() => {
                this.messages.push({content: "You have been disconnected"});
            });
        });
        this.socket.addEventListener('error', event => {
            console.log("The socket had an error", event.error);
        });
    }
 
    public ngOnDestroy() {
        this.socket.close();
    }
 
    public send() {
        if(this.chatBox) {
            this.socket.send(this.chatBox);
            this.chatBox = "";
        }
    }
 
}
I am using node.js at server side.

After running i get error->
The socket had an error java.net.ConnectException: Connection refused.

I don't have any idea regarding socket connection. I am trying first time.Any idea why i getting these error?

Thanks.

**Comment by NathanaelA** [comment]
Try changing that from: `http://192.168.3.41:2018/` to `ws://192.168.3.41:2018`

**Comment by SumanSingh4** [comment]
I try it but didn't work. Getting same error .

**Comment by NathanaelA** [comment]
There are a couple things.
1. If you are running from an emulator; that ip address may not be valid (depending on how your network is setup).
2. If you are running from your phone, are you sure your computer is allowing that ip address to be published.
3. Are you sure you are using a WebSocket library and not something like Socket.io; socket.io uses websockets but normal WS can't connect to a socket.io server...    You can try by taking normal WS code and trying it in your browser and verify your browser can connect using standard WS commands.

**Comment by SumanSingh4** [comment]
Oh Thanks for pointed out reasons. 

I find my issue. point 3 is the reason. I am using socket.io. 
Now i changed my plugin to nativescript-socketio. Its working now.

Thanks for your help.
