### ISSUE TITLE
Getting websocket error code 1006 in iOS.

### ISSUE THREAD

**Issue by viniciodeltoro** [NathanaelA/nativescript-websockets#25]
I'm using an Actioncable js file to connect to an Actioncable rails server. This actioncable js file uses this nativescript-websockets plugin.
I have been doing connection testing on Android and it works properly, the connection works properly on the web browser as well but when I run it on iOS I get an error like this:
`Socket was closed because:    code:  1006`
This [link](http://stackoverflow.com/questions/19304157/getting-the-reason-why-websockets-closed) explains that the connection gets closed abnormally because some incompatibility between the server and the client. I don't really know can can be the issue.
I did [post](http://stackoverflow.com/questions/43175006/getting-websocket-error-code-1006-when-trying-to-connect-to-actioncable-server) in Stackoverflow since I thought the issue was happening because of the protocols used (actioncable-v1-json, actioncable-unsupported), but even if I don't provide these protocols on the browser test, the connection still works.

Any ideas on what is causing this issue?
Thanks

**Comment by NathanaelA** [comment]
Does your server by any chance have compression on.  Someone reported compression was broken on iOS a while ago; and I haven't had a chance to verify or do anything about it if it is...   Disabling compression would fix the issue.

**Comment by dapperapps** [comment]
+1 having same issue

**Comment by zahid-dapperapps** [comment]
@viniciodeltoro  Please share server code. Have you compared between request that is recevied from iOS and request that is recevied from android builds

**Comment by viniciodeltoro** [comment]
Sorry I don't have the code anymore I ended up switching to socket.io and using a Node server dedicated for websocket communications only.

**Comment by zahid-dapperapps** [comment]
I have provided a solution here that can be helpful. It has worked for me http://stackoverflow.com/a/43952323/319297

**Comment by soulfly** [comment]
Had the same issues recently, 

In my case it was a problem in WebSocket rfc6455 - different implementation on client and server
and the issue was with dependant iOS lib PocketSocket

More details here
https://github.com/zwopple/PocketSocket/issues/73

So I simply added 

`this._headers['Connection'] = "Upgrade";`
after
`this._headers = options.headers || [];`

in websockets.ios.js file

**Comment by NathanaelA** [comment]
This fix Igor provided has been present in v1.4 or later.   If anyone has any more issues with iOS please open a new issue.
