### ISSUE TITLE
secure socket (wss) not working in ios

### ISSUE THREAD

**Issue by sud80** [NathanaelA/nativescript-websockets#27]
We are  using the nativescript-websockets 1.3.3. Everything works perfectly fine if I use the ws protocol. Once I switch to wss protocol (we have valid trusted ssl certificate), it hangs in ios after calling the socket.open. In android both ws and wss works fine. 
Anybody else faced this issue on ios?

**Comment by zahid-dapperapps** [comment]
which server for websocket are you using? can you share code?

**Comment by sud80** [comment]
So it is basically phoenix server behind aws elb (with tls v1.2 support). I am able to connect to this server thro' wss from my android version of the app and from browser as well. Basically the connection is not getting established and just hangs. I thought initially probably ssl handshake issue. So I explicitly added settings in info.plist to allow tls v1.1 and forwardsecrecy set to false. But still the same issue.

My client code looks something like:
        this.conn = new WebSocket(this.endPointURL(), {timeout: this.timeout});
        this.conn.open();
        this.conn.on('open', function(socket) { return _this5.onConnOpen(); });
        this.conn.on('message', function(socket, message) { return _this5.onConnMessage(message); });
        this.conn.on('close', function(socket, code, reason) { _this5.onConnClose(reason); });
        this.conn.on('error', function(socket, error) { return _this5.onConnError(error); });

**Comment by NathanaelA** [comment]
You might need to check the full logs (not the truncated logs that TNS produces) of the connection.    
If you can duplicate this issue, try looking at my blog and getting the full log and posting it.
http://fluentreports.com/blog/?p=545

**Comment by sud80** [comment]
@ChrisFromCanada 
So it turned out to be an issue that, if the socket.isConnected function is invoked while the socket connection is in progress causes it to hang. So I changed my code to make sure the isConnected is not invoked while the connection is in progress. That fixed it for me.
