### ISSUE TITLE
Error when requiring nativescript-sockets

### ISSUE THREAD

**Issue by mitkodkn** [NathanaelA/nativescript-websockets#3]
I get this error when I require the module in a JavaScript file:
![screenshot](https://cloud.githubusercontent.com/assets/3275194/10414135/f1627158-6fcc-11e5-9865-82971376c0af.png)
What should I do to get rid of it? (the blurred area is the hidden namespace of the application)

**Comment by AvagArakelyan** [comment]
Try to build your project after you have included `native-websockets` module. This could be done by `tns build {plaform}` command.

**Comment by NathanaelA** [comment]
@mitkodkn -- I'm sorry I didn't get a notification of an issue.  Not sure what happened.   

This is acting like you don't have the websockets library getting built into the application.  
1. What version of NativeScript? (tns --version) 
2. What version of the Android runtimes. (inside the package.json file)

**Comment by NathanaelA** [comment]
If you can still cause this issue; let me know.  Otherwise I assume you got it fixed and so I am closing it.
