### ISSUE TITLE
Can't build my project with aot when i following your example

### ISSUE THREAD

**Issue by gtzinos** [NathanaelA/nativescript-websockets#31]
Your ng example: https://www.thepolyglotdeveloper.com/2017/01/communicate-with-websockets-in-a-nativescript-angular-application/

This line is wrong:
require("nativescript-websockets");

Error message:
Module not found: Error: Can't resolve 'nativescript-websockets' in '/myfolder/myfile'

**Comment by cmargulhano** [comment]
Same here

**Comment by NathanaelA** [comment]
I have fixed the issue for webpacking in the release  1.3.4
