### ISSUE TITLE
Doesnot work in Webpack

### ISSUE THREAD

**Issue by cmargulhano** [NathanaelA/nativescript-websockets#33]
I made it in my app.module:

if (global.TNS_WEBPACK) {
    require("globals");
    global.registerModule("nativescript-websockets", () => require("../node_modules/nativescript-websockets/websockets-common"));
}

And in my component:

if (global.TNS_WEBPACK) {
    global.loadModule("nativescript-websockets");
 } else {
    require('nativescript-websockets');
 }

And I received this error in runtime:

JS: Uncaught Error: com.tns.NativeScriptException: Failed to find module: "nativescript-websockets", relative to: app/tns_modules/
JS:     com.tns.Module.resolvePathHelper(Module.java:146)
JS:     com.tns.Module.resolvePath(Module.java:55)
JS:     com.tns.Runtime.runWorker(Native Method)
JS:     com.tns.Runtime.access$1600(Runtime.java:34)
JS:     com.tns.Runtime$WorkerThread$1.run(Runtime.java:330)
JS:     android.os.Handler.handleCallback(Handler.java:751)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:154)
JS:     android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by NathanaelA** [comment]
This should now be fixed in the version I pushed today.
