### ISSUE TITLE
Exception: org.java_websocket.exceptions.InvalidFrameException: more than 125 octets

### ISSUE THREAD

**Issue by pushkardeshmukh1992** [NathanaelA/nativescript-websockets#34]
Hi,

I am trying to connect to Pusher using 
`    let mySocket = new WebSocket("ws://ws.pusherapp.com:80/app/<key>");
`

Socket is getting closed with the following exception as soon as it opens
`org.java_websocket.exceptions.InvalidFrameException: more than 125 octets`

What could be the possible reason?

**Comment by NathanaelA** [comment]
Please retest in the new v1.4.0...
