### ISSUE TITLE
Connection establishes in iOS, but method "send" is not working

### ISSUE THREAD

**Issue by lovemakeri** [NathanaelA/nativescript-websockets#39]
I am using plugin version 1.4.0 of nativescript-websockets. Connection establishes fine, but when it comes to "send" method, app does not throw any errors and nothing happens, websocket on server does not receive any messages. "Message" event does not work too. "Close" and "Error" events work fine. I have tried both "ws" and "wss" protocols. In Android everything works perfectly. I have tried both advanced and browser based interface. 

Can you give me any insight how to solve this issue? 

Details:
Machine: Mac OS High Sierra v10.13.2
Cocoapods: v1.3.1
NativeScript (tns --version): v3.3.0
Angular: v4.4.1
Xcode: v9.2

**Comment by NathanaelA** [comment]
I would have to have a demo project to diagnose the issue.   I just tested it and it is working fine for me on both iOS and Android.
