### ISSUE TITLE
Build fail with {N} + Vue.js

### ISSUE THREAD

**Issue by bonustrack** [NathanaelA/nativescript-websockets#43]
The plugin `nativescript-websockets` make build failing with {N} + Vue.js with this error:
![image](https://user-images.githubusercontent.com/16245250/37809826-9ef0ecd8-2e83-11e8-862c-69d79a07dbb3.png)

**Comment by NathanaelA** [comment]
Those are warnings; one of them is caused by vscode; the other is telling you the podfile didn't specify ios; but it set it to ios for you.    Neither of those warnings should have caused it to fail.
