### ISSUE TITLE
Add an emphasized mention to NgZone in the doc

### ISSUE THREAD

**Issue by gdurand** [NathanaelA/nativescript-websockets#44]
I know that the tutorial mentions the problem with UI updates with Angular, but I accidentally skipped this while reading the insane amount of docs required to start a nativescript project.
I think something in bold, red and blinking about the usage of NgZone in the doc file would attract more attention and prevent people to lose so much time with non-working UI updates.

**Comment by NathanaelA** [comment]
Were you meaning to post this to the general nativescript angular repo https://github.com/NativeScript/NativeScript-angular -- Or was there something you ran into specifically with my Websocket plugin?

**Comment by gdurand** [comment]
I guess it can apply to nativescript (or rather angular) in general, but it is especially relevant for this library because if you use standard nativescript libs you don't run into this kind of advanced topic (from my very limited experience).
The real issue is I didn't read properly the tutorial, but a more formal warning in the doc about using NgZone.run() in callbacks if they should trigger UI updates may help others.

**Comment by NathanaelA** [comment]
Thank you; I have added this to the next versions doc's.
