### ISSUE TITLE
Support wss with self-signed certificates in Android

### ISSUE THREAD

**Issue by gdurand** [NathanaelA/nativescript-websockets#45]
This could be done by allowing to set a default SSLSocketFactory, so we can pass the usual factory with no trustmanager, or even with an explicit support, which would avoid people to manage this kind of thing.

The former is probably better because is allows more control, and you have to go through hoops anyway if you want this support for https (not possible with the android client, so you have to use okhttp directly).

My quick hack:
In the  constructor:
```
this._sslSocketFactory = options.sslSocketFactory;
```

In _reCreate:
```
if (isWSS) {
		var socketFactory;
		if (this._sslSocketFactory) {
			socketFactory = this._sslSocketFactory;
		} else {
			//noinspection JSUnresolvedFunction,JSUnresolvedVariable
			var sslContext = javax.net.ssl.SSLContext.getInstance( "TLS" );
			sslContext.init( null, null, null );
			//noinspection JSUnresolvedFunction
			socketFactory = sslContext.getSocketFactory();
			//noinspection JSUnresolvedFunction
		}
		
		this._socket.setSocket( socketFactory.createSocket() );
}
```

**Comment by NathanaelA** [comment]
Thank you for the idea.  I have implemented this in the next version.  `options.sslSocketFactory` can be set on Android to pass in your own socket factory.

**Comment by yenjcc** [comment]
This not works for me
