### ISSUE TITLE
Occasional WebsocketNotConnectedException

### ISSUE THREAD

**Issue by Nestorferrando** [NathanaelA/nativescript-websockets#53]
Hi! we are using version 1.5.0 of this great plugin.

Very occasionally we are getting a  org.java_websocket.exceptions.WebsocketNotConnectedException on the android runtime:

This is the full stacktrace:

System.err: com.tns.NativeScriptException:
System.err: Calling js method run failed
System.err:
**System.err: Error: org.java_websocket.exceptions.WebsocketNotConnectedException
System.err: org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
System.err: org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
System.err: org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)**
System.err: com.tns.Runtime.callJSMethodNative(Native Method)
System.err: com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: android.os.Handler.handleCallback(Handler.java:751)
System.err: android.os.Handler.dispatchMessage(Handler.java:95)
System.err: android.os.Looper.loop(Looper.java:154)
System.err: android.app.ActivityThread.main(ActivityThread.java:6077)
System.err: java.lang.reflect.Method.invoke(Native Method)
System.err: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
System.err: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
System.err: File: "file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/nativescript-websockets/websockets.js, line: 529, column: 19
System.err:
System.err: StackTrace:
**System.err: Frame: function:'NativeWebSockets._send', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/nativescript-websockets/websockets.js', line: 529, column: 20
System.err: Frame: function:'NativeWebSockets.send', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/nativescript-websockets/websockets.js', line: 490, column: 10
System.err: Frame: function:'',** file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 3692, column: 27
System.err: Frame: function:'', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 8061, column: 9
System.err: Frame: function:'process', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 6309, column: 17
System.err: Frame: function:'', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 6217, column: 19
System.err: Frame: function:'', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 4098, column: 16
System.err: Frame: function:'Item.run', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 9881, column: 14
System.err: Frame: function:'drainQueue', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/stanza-io/stanza-io.js', line: 9851, column: 42
System.err: Frame: function:'invoke', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
System.err: Frame: function:'run', file:'file:///data/data/com.nospoonlab.neodev/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13
System.err:
System.err: at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: at android.os.Handler.handleCallback(Handler.java:751)
System.err: at android.os.Handler.dispatchMessage(Handler.java:95)
System.err: at android.os.Looper.loop(Looper.java:154)
System.err: at android.app.ActivityThread.main(ActivityThread.java:6077)
System.err: at java.lang.reflect.Method.invoke(Native Method)
System.err: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
System.err: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
System.err: Caused by: org.java_websocket.exceptions.WebsocketNotConnectedException
System.err: at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:608)
System.err: at org.java_websocket.WebSocketImpl.send(WebSocketImpl.java:585)
System.err: at org.java_websocket.client.WebSocketClient.send(WebSocketClient.java:309)
System.err: ... 14 more

**Comment by NathanaelA** [comment]
@Nestorferrando - Thanks for the call stack.  I have added some code to v1.5.1 that should handle this case.  Apparently at some point between me checking the status and trying to send the socket was closed.   It should now handle this case properly...
