### ISSUE TITLE
iOS issues

### ISSUE THREAD

**Issue by ineiti** [NathanaelA/nativescript-websockets#55]
I still have many issues using this library in iOS. I'm using it to talk to a remote go-websocket sending and receiving protobuf-messages, and I have timeouts, messages sent badly (I opened #54 for that) and sometimes a `1002` websocket error.

I'm using the latest nativescript (4.2.3) and nativescript-websockets 1.5.2. I tried both the 'browser' websocket and the advanced interface.

Before I loose my mind, is iOS tested and supported? From my point of view it looks as not... Android works great, by the way, with exactly the same code!

**Comment by NathanaelA** [comment]
Both iOS & android is tested and supported.

**Comment by ineiti** [comment]
Nice to hear it's tested, so I'm doing something terribly wrong. I set up the simplest program I could imagine, here:

https://github.com/dedis/popcoinsY/blob/master/app/tests/websocket.js#L64

It runs if I do:

```
tns test android
```

but if I do

```
tns test ios
```

It fails after one or two successful messages (yes, OR, sometimes it manages to do more than one message, sometimes not...). This looks to me like the message gets truncated somewhere. But I think it's strange that android puts together the messages, while ios doesn't... If it fails on the first message, it always gets 2253 bytes, on the third message it's 2186 bytes.

Any help in debugging this would be greatly appreciated.

```
CONSOLE LOG file:///app/tests/websocket.js:24:20: connecting to: ws://gasser.blue:7003/PoPServer/GetInstanceID
CONSOLE LOG file:///app/tests/websocket.js:56:20: opening
CONSOLE LOG file:///app/tests/websocket.js:28:24: sending data: 0a20b73b5efd15eb6bd808da4ae7ecd0c696f505172dddfa045aa063c8f92506df05
CONSOLE LOG file:///app/tests/websocket.js:7:20: received message: length = 34
CONSOLE LOG file:///app/tests/websocket.js:38:28: data is correct
CONSOLE LOG file:///app/tests/websocket.js:24:20: connecting to: ws://gasser.blue:7003/OmniLedger/GetProof
CONSOLE LOG file:///app/tests/websocket.js:56:20: opening
CONSOLE LOG file:///app/tests/websocket.js:48:24: closing: 1000 null
CONSOLE LOG file:///app/tests/websocket.js:28:24: sending data: 0802122000000000000000000000000000000000000000000000000000000000000000001a200d75236a47c8b61b27b47da1df6af68e793ae68fa895eed95c6e5310846d5eab
CONSOLE LOG file:///app/tests/websocket.js:7:20: received message: length = 2253
CONSOLE LOG file:///app/tests/websocket.js:41:28: wrong data
CONSOLE LOG file:///app/tests/websocket.js:7:20: original: length = 4056
CONSOLE LOG file:///app/tests/websocket.js:48:24: closing: 1000 null
```

**Comment by ineiti** [comment]
And now I got my favourite message:

```
closing: 1002 Failed to inflate bytes
```

I'm doing something wrong, I know...

**Comment by ineiti** [comment]
OK - `inflate`, `deflate`, compression... Now I changed my golang-webserver to:

```
websocket.Upgrader{
  EnableCompression: false,
}
```

before it was on `true`. All of a sudden it works very well. So if somebody reads this in the future, try to turn off compression on the server.

And if there is any way I can help debugging this error, I'm happy to do so.

**Comment by NathanaelA** [comment]
Yeah, compression on iOS seems to be a bit flaky with some servers.   I'm not sure which side it is; but I've seen reports for a while that really random issues issues with it.

**Comment by ineiti** [comment]
Is it possible to disable compression per default in iOS? That would kind of cover the problem...

**Comment by ineiti** [comment]
Are there any other things that are flaky from time to time? I'm still having a hard time communicating with my go-server with iOS, while Android communicates without any problem.

**Comment by webleaf** [comment]
@NathanaelA there are also issue #65 (is it still actual?)
I worry to use this plugin, because of ios-part of this plugin seems not stable.
May be we should use [Starscream](https://github.com/daltoniam/Starscream) instead [PocketSocket](https://github.com/zwopple/PocketSocket)?

**Comment by ineiti** [comment]
As I wrote in #65, at least here it works fine. And I'm doing quite nasty, non-optimal usage of websockets, with many open connections.

**Comment by NathanaelA** [comment]
I have tested this on iOS 14.7 and w/ NS 8.0 and the demo app seems to be working fine.      However, my server has deflate turned off, so it is very likely an issue with the underlying PocketSocket library.    I have debated replacing the underlying library from PocketSocket to a different one, but that requires time.
