### ISSUE TITLE
off/removeEventListener doesn't work for a specified callback

### ISSUE THREAD

**Issue by Ethan-Bi** [NathanaelA/nativescript-websockets#57]
Hi, 

When i try to remove a specific callback from an event, eg:
socket.off("message", callback), the callback can not be removed actually.

I did a little investigation to the source code, i guess the issue is caused by a typo in the code.

```js
        for (var i=eventCallbacks.length-1;i>=0;i--) {
            if (eventCallbacks[i].c === callback) {
                eventCallbacks.slice(i, 1);
            }
        }
```
I believe the "slice" in the NativeWebSockets.prototype.removeEventListener function should be "splice".

Let me know if i am wrong, thanks!

**Comment by NathanaelA** [comment]
You are correct, this is supposed to be a `splice`.      Thanks for catching it...

**Comment by NathanaelA** [comment]
I have updated both Android and iOS in my master copy.  I have another issue I need to look into and then I should have another release soon.

**Comment by Ethan-Bi** [comment]
thanks, looking forward to your new release.
