### ISSUE TITLE
WSS TLS 1.2 not supported

### ISSUE THREAD

**Issue by aminebizid** [NathanaelA/nativescript-websockets#58]
On old android devices, I get the error below because TLS 1.2 can't be used:

JS: Error: Failed to start the transport 'WebSockets': javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xb944f950: Failure in SSL library, usually a protocol error
JS: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x8d985990:0x00000000)
JS: Error: Failed to start the connection: Error: Unable to initialize any of the available transports.
chromium: [ERROR:ssl_client_socket_openssl.cc(197)] OpenSSL SYSCALL error, earliest error code in error queue: 0, errno: 0
chromium: [ERROR:ssl_client_socket_openssl.cc(870)] handshake failed; returned 0, SSL error code 5, net_error -107

**Comment by NathanaelA** [comment]
What device OS?

**Comment by hiperbou** [comment]
This error appears on Android versions < 5.0
I can reproduce that with an Android 4.4.4.

**Comment by nikoTM** [comment]
@NathanaelA any specific reasons for not updating `websockets.jar` to use the latest release of `Java-WebSocket`?

**Comment by NathanaelA** [comment]
@nikoTM - No real reason other than no time to do tests.  But I love PR's.

**Comment by NathanaelA** [comment]
The Websocket jar was updated to the latest in v2.0
