### ISSUE TITLE
libSystem.dylib

### ISSUE THREAD

**Issue by Tim-W** [NathanaelA/nativescript-websockets#6]
I cannot find the file libSystem.dylib when i try to add it to the Linked Frameworks and Libraries for iOS build. Is there a replacing file for this?

Using iOS 9.2, XCode 7.2.

**Comment by NathanaelA** [comment]
Hmm, not sure; I have XCode 7.2 now; but I haven't tried to install WebSockets on it yet.   I do have a rework of the project coming up to make it into a Cocoapod since I prefer everything to be automatic.   If you can wait a couple days; this should be done as it is next on my list to do.

**Comment by NathanaelA** [comment]
I should note; when  I wrote this plugin I was using Maveriks and XCode 5.   So that was the proper way to do it.   But I believe switching it to a CocoaPod will make it a simple install rather than you having to make any changes to the project.

**Comment by NathanaelA** [comment]
I just released v1.10 of the Websocket library which now uses Cocoapod for the support; I have tested it on my XCode 7.x and IOS 9.x and it builds and runs without ANY manual steps now.  Just do a tns plugin add nativescript-websockets.
