### ISSUE TITLE
ios 30s the socket close code 1000

### ISSUE THREAD

**Issue by liutao0617** [NathanaelA/nativescript-websockets#61]
![image](https://user-images.githubusercontent.com/7960441/49370012-e1e0df80-f72d-11e8-84d7-0f01d88e8a5a.png) 
After 30 seconds, the socket will automatically disconnect and return to code1000.

**Comment by romandragan** [comment]
Same for me

**Comment by NathanaelA** [comment]
Make sure your server has compression turned off, on iOS  compression seems to be very flaky.
