### ISSUE TITLE
v1.5.3 crashes in iOS with latests {N} playground/preview with web based dev

### ISSUE THREAD

**Issue by MpeStuntPilot** [NathanaelA/nativescript-websockets#64]
With the latest iOS installed on iPhone XR, using the latest {N}playground & preview,  with web based dev tool on Safari, with nativescript-websockets in the project (ver 1.5.3 from package.json)

var WS = require('nativescript-websockets'); 

crashes with "Can't find variable: PSWebSocketDelegate".

**Comment by NathanaelA** [comment]
Well considering the NS-Websockets is a compiled plugin; it isn't expected to work in the Progress playground.  The Progress Playground has a limitation on using any plugins that have any compiled resources or compiled code.  They won't work.   This is a Progress Playground issue; not a plugin issue.
