### ISSUE TITLE
iOS app is crashing when send or receive on devices iOS 12 or later

### ISSUE THREAD

**Issue by melaniol** [NathanaelA/nativescript-websockets#65]
Hi, i am new on this platform, i have an issue, when i work on iPhone 5, 5s, 6 or 6S my app is working fine with this plugin (really nice), but when i had test it on iPhone XS (i was thinking that it was the devices), it crash and close it. On Android is working fine in any version, but so long time from testing the problem is not iPhone XS, is on devices iOS12 or plus  it crash. In Simulator the console does not emit any message for helpme, just close the app and i have to enter. 

Anyone have this same problem, what i need for than you understand my question?

Thanks in advance.

**Comment by NathanaelA** [comment]
Does it crash in the iOS 12 XS Simulator or only on a  real device

**Comment by melaniol** [comment]
Both devices. I was thinking just in Simulator, but when i tested on real devices it works (iPhone 6S or less) but when i had a oportunity from test on iPhone X and XR real devices it crash. After long testing i discovered than was in devices with iOS 12 or later.

**Comment by ulversson** [comment]
I am having the same problem. The crash happens as soon as you call 'open' method to open connection to websocket server.

**Comment by ineiti** [comment]
Hi there - I just tried it on a simulator with an iPhoneX and iOS 12.4. And the library seems to work fine here.

There was a problem in the past with compressed connections, so I put the server on `EnableCompression: false`, and it works without problems.

**Comment by NathanaelA** [comment]
I have tested on a real iOS 14 device today and it was working fine for me.   Please test the demo and see if it fails.
