### ISSUE TITLE
Support send callback

### ISSUE THREAD

**Issue by dosomder** [NathanaelA/nativescript-websockets#78]
The nodejs websocket implementation supports a callback for the send method. See https://github.com/websockets/ws/blob/master/doc/ws.md#websocketsenddata-options-callback

Would this be possible to implement?

**Comment by NathanaelA** [comment]
Problem is that the underlying OS (& Libraries) handles it on the phone, I don't know when the actual data is written and sent to the other side.   But you can easily add your own code to the server side that when you get a message, you send a message back to the device acknowledging the message.
