### ISSUE TITLE
wss (secure websockets) not working on android

### ISSUE THREAD

**Issue by benkaiser** [NathanaelA/nativescript-websockets#8]
When I use a wss url, it fails.

It gives me the following error:

```
JS: Socket had an error javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
JS: Socket was closed because:  java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.  code:  -1
```

Any information on the status of this?

**Comment by NathanaelA** [comment]
I believe this means that the Android OS thinks your ssl certificate is invalid.   See: 
http://stackoverflow.com/questions/6825226/trust-anchor-not-found-for-android-ssl-connection for some help on how to resolve this error.

**Comment by benkaiser** [comment]
I have the same secure websocket connection used in the browser (tested in chrome on my android device), and it has no issues with the certificate. It is only within the nativescript-websocket connection that it throws this error.

**Comment by NathanaelA** [comment]
Do you have a site that I can try this against to see if something broke?

**Comment by benkaiser** [comment]
Sure, here's the websocket endpoint:
```
wss://personal.kaiserapps.com/socket.io/?EIO=3&transport=websocket
```
If you load https://personal.kaiserapps.com you'll notice in the network tab (filter to WS type) that the connection is made fine.

But then if you make that connection in nativescript-websockets it gives that above error.

**Comment by NathanaelA** [comment]
Hmm, interesting it does appear like FF & Chrome are connection (although they are not doing anything with the socket, no data was passed on it).    
I'll see why the Websockets isn't connecting properly.

**Comment by sunny061** [comment]
Any updates on this issue?

**Comment by NathanaelA** [comment]
@sunny061 - Nope; I haven't had a chance to dive into it, any paid work has priority over this free stuff.  Just to set the expectation properly, I Probably still won't until sometime in Nov at the earliest.

**Comment by shantanubhadoria** [comment]
Hi NathanaelA,
Thank you for this module. Does this mean that wss is not supported?

**Comment by NathanaelA** [comment]
@shantanubhadoria wss should be supported; but it is possible that either there is a bug in this implementation or there was a bug in the server side.   When I have a chance to dig into it; I'll know...  But feel free to try it and let me know what happens..

**Comment by shantanubhadoria** [comment]
I tried it on my comodo SSL certified certificate and it seems to work fine with ssl there. Perhaps the trouble is with self signed certificates?

**Comment by FmarquezM** [comment]
Same result here, wss fails with a self-signed certificate and working right with a certificate generated with "let's encrypt" ([https://letsencrypt.org/]).

Nathanael, thanks a lot for the plugin !!

**Comment by sunny061** [comment]
My issue was also resolved when I changed the self signed certificate. Self signed don't seem to work.

**Comment by bferreirainfo** [comment]
in my case i cant change the certificate, how can ignore this erro and do the request anyway?

**Comment by rudzikdawid** [comment]
Yep, the same issue
I installed .crt on android, after that, Chrome browser connects via wss without any problem.
But nativescrip .apk can't
```
JS: Socket had an error javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
JS: Socket was closed because:  java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.  code:  -1
```

**Comment by zenchanhk** [comment]
Is it possible to specify a `ca` certificate in the option?

**Comment by NathanaelA** [comment]
I haven't tried recently; but the issue with setting up the SSL session from inside NativeScript probably is fixed --  If it is you can enable the code TLS/SSL socket setup code here:
https://github.com/NathanaelA/nativescript-websockets/blob/master/websockets.android.js#L245
Just disable the line of code that calls the internal setup function and uncomment the NS code below it.

And then you are free to add any additional items to the tls socket setup like your own certs...

**Comment by zenchanhk** [comment]
Hi NathanaelA, thanks for your clue. It seems I can specify a `ca` certificate in `sslContext.init( null, null, null );`, I will try it out. But I can't find similar lines in iOS implementation, is it possible in iOS implementation? Thanks again.

**Comment by NathanaelA** [comment]
v.1.4 re-sets the WSS to be setup in NativeScript in Android, so let me know if anyone has any wss issues on Android.

**Comment by NathanaelA** [comment]
As for iOS, I have no idea.  Sorry.  If anyone has wss working with custom certificates; please post how.
