### ISSUE TITLE
source websocket.jar

### ISSUE THREAD

**Issue by saschaarthur** [NathanaelA/nativescript-websockets#84]
Can we have the source for websocket.jar please?

Is it this repo here? https://github.com/NathanaelA/NS-JavaWebsocket

**Comment by NathanaelA** [comment]
Yep, that is the correct repo.  :)

**Comment by saschaarthur** [comment]
This repo seems not to be the code out of the jar which is included here..

Theres for example

org\java_websocket\protocols\Protocol.class

which is not included in 

https://github.com/NathanaelA/NS-JavaWebsocket

**Comment by NathanaelA** [comment]
It is possible that the code is now straight from the original author's repo (https://github.com/TooTallNate/Java-WebSocket) .  Have you double checked that?       I recall the first version I had to do a lot of work arounds, but it seems like later versions I didn't have as many...
