### ISSUE TITLE
Compatible with NativeScript 7 and iOS 14?

### ISSUE THREAD

**Issue by jessorlisa** [NathanaelA/nativescript-websockets#88]
Is this package compatible with the latest NativeScript 7 and iOS 14?

Thanks for a short feedback! ;)

**Comment by NathanaelA** [comment]
Hi @jessorlisa - Sorry, honestly have not had time to test it.   I don't see any reason it wouldn't be...

**Comment by tralves** [comment]
@jessorlisa did you test it in NS7? Did it work?

**Comment by jessorlisa** [comment]
It is working with {N} 7 and the JSC runtime:
```
├── nativescript@7.0.11
├── @nativescript/core@7.0.13
├── @nativescript/ios@6.5.3 <--- latest JSC version
```
We had too many issues with the v8 runtime (not only with this plugin) so we downgraded to the JSC runtime.
