### ISSUE TITLE
Change code on README

### ISSUE THREAD

**Issue by h-nasu** [NathanaelA/nativescript-websockets#9]
`MySocket.on('error', function(socket, error) { console.log("Socket had an error", error);});`
to
`mySocket.on('error', function(socket, error) { console.log("Socket had an error", error);});`

**Comment by NathanaelA** [comment]
@h-nasu - Ah, yeah good catch.

**Comment by NathanaelA** [comment]
Thanks again, I have updated the docs in v1.2 to fix that silly typo.
