### ISSUE TITLE
NS8 Angular 12 TypeError: wrapper._notify is not a function

### ISSUE THREAD

**Issue by wuilmerj24** [NathanaelA/nativescript-websockets#93]
I am trying to connect as follows 
`new WebSocket("ws://e**.net/ServicesHub?id=" + result,["WebSockets"]);`

`System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method run failed
System.err: TypeError: wrapper._notify is not a function
System.err: 
System.err: StackTrace:
System.err: (file: src/webpack:/europ-new/node_modules/@master.technology/websockets/websockets-base.android.js:60:0)
System.err:     at timer(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:2561:0)
System.err:     at invokeTask(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:406:0)
System.err:     at runTask(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:178:0)
System.err:     at invokeTask(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:487:0)
System.err:     at ZoneTask.invoke(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:476:0)
System.err:     at data.args.<computed>(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:2541:0)
System.err:     at invoke(file: src/webpack:/europ-new/node_modules/@nativescript/core/timer/index.android.js:18:0)
System.err:     at invoke(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:372:0)
System.err:     at runGuarded(file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:144:0)
System.err:     at (file: src/webpack:/europ-new/node_modules/zone.js/fesm2015/zone.js:128:0)
System.err:     at run(file: src/webpack:/europ-new/node_modules/@nativescript/core/timer/index.android.js:22:0)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.java.lang.Runnable.run(Runnable.java:17)
System.err:     at android.os.Handler.handleCallback(Handler.java:790)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
`

**Comment by NathanaelA** [comment]
Try v2.01 -- I believe this should be fixed.

**Comment by wuilmerj24** [comment]
@NathanaelA Okay. Thnks.
