### ISSUE TITLE
Warnings about missing `org.slf4j.impl.StaticLoggerBinder`

### ISSUE THREAD

**Issue by wSedlacek** [NathanaelA/nativescript-websockets#95]
When using this plugin with Android I get the following warning messages on startup.

```
System.err: SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
System.err: SLF4J: Defaulting to no-operation (NOP) logger implementation
System.err: SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

While I appreciate the notice this provides about a missing class, I feel that adding this class would offer me little benefit within the context of NativeScript.

**Comment by NathanaelA** [comment]
This is normal because the Android library I'm using for the low level websockets uses this as a logger if it is available, otherwise it throws an error.

**Comment by wSedlacek** [comment]
Solved by adding the following to `app.gradle` 

```
compile 'org.slf4j:slf4j-nop:1.7.25'
```
